import type { Building } from "@/types";

const NOW = "2026-01-01T00:00:00.000Z";

/** Local fallback — mirrors supabase/migrations/001_initial_schema.sql seed data. */
export const BUILDINGS_SEED: Building[] = [
  {
    id: "stem-building",
    name: "STEM Building",
    code: "STEM",
    lat: 34.2442,
    lng: -92.0237,
    description:
      "State-of-the-art facility supporting science, technology, engineering, and mathematics research across campus.",
    image_url: null,
    floors: 4,
    year_built: 2016,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "woodward-hall",
    name: "Woodward Hall",
    code: "WWH",
    lat: 34.244,
    lng: -92.0221,
    description: "Instructional facility for science and engineering programs.",
    image_url: null,
    floors: 3,
    year_built: null,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "holiday-hall",
    name: "Holiday Hall",
    code: "HLD",
    lat: 34.2435,
    lng: -92.0221,
    description:
      "Residential and administrative hall supporting student and faculty activities.",
    image_url: null,
    floors: 3,
    year_built: null,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "walker-research-center",
    name: "Walker Research Center",
    code: "WRC",
    lat: 34.2436,
    lng: -92.0213,
    description: "Dedicated research facility for applied sciences and engineering.",
    image_url: null,
    floors: 2,
    year_built: null,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "caldwell-hall",
    name: "Caldwell Hall",
    code: "CALD",
    lat: 34.2422,
    lng: -92.0196,
    description:
      "Home to biology and agricultural sciences programs with active field and lab research.",
    image_url: null,
    floors: 3,
    year_built: 1958,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "la-davis-student-union",
    name: "L.A. Davis Sr. Student Union",
    code: "LDSU",
    lat: 34.2429,
    lng: -92.0226,
    description:
      "Central campus hub connecting students, faculty, and community outreach programs.",
    image_url: null,
    floors: 2,
    year_built: 1985,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "henderson-young-hall",
    name: "Henderson-Young Hall",
    code: "HYH",
    lat: 34.2423,
    lng: -92.0213,
    description: "Academic and administrative building supporting multiple departments.",
    image_url: null,
    floors: 3,
    year_built: null,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "caine-gilleland-hall",
    name: "Caine-Gillelean Hall",
    code: "CGH",
    lat: 34.2414,
    lng: -92.021,
    description: "Academic hall housing classroom and laboratory spaces.",
    image_url: null,
    floors: 2,
    year_built: null,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "dawson-hicks-hall",
    name: "Dawson-Hicks Hall",
    code: "DHH",
    lat: 34.2413,
    lng: -92.0202,
    description: "Instructional building with classroom and office spaces.",
    image_url: null,
    floors: 2,
    year_built: null,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "corbin-hall",
    name: "Corbin Hall",
    code: "CBH",
    lat: 34.2407,
    lng: -92.0209,
    description: "Multi-purpose academic facility.",
    image_url: null,
    floors: 2,
    year_built: null,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "rust-technology-building",
    name: "Rust Technology Building",
    code: "RTB",
    lat: 34.2408,
    lng: -92.0225,
    description: "Home to engineering technology programs with lab and maker spaces.",
    image_url: null,
    floors: 2,
    year_built: null,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "human-sciences-building",
    name: "Human Sciences Building",
    code: "HSB",
    lat: 34.244,
    lng: -92.02,
    description: "Houses human sciences, nutrition, and social work programs.",
    image_url: null,
    floors: 2,
    year_built: null,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "john-b-watson-library",
    name: "John B. Watson Library",
    code: "JBWL",
    lat: 34.2421,
    lng: -92.0223,
    description: "Main campus library providing research resources and study spaces.",
    image_url: null,
    floors: 3,
    year_built: null,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "parker-1890-complex",
    name: "S.J. Parker 1890 Extension Complex",
    code: "1890",
    lat: 34.2515,
    lng: -92.0239,
    description:
      "Extension complex supporting 1890 land-grant research and community outreach programs.",
    image_url: null,
    floors: 2,
    year_built: null,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "parker-ag-research",
    name: "S.J. Parker Agriculture Research Bldg",
    code: "PARB",
    lat: 34.2526,
    lng: -92.0242,
    description: "Applied research in sustainable agriculture, soil science, and food systems.",
    image_url: null,
    floors: 1,
    year_built: 2001,
    created_at: NOW,
    updated_at: NOW,
  },
];
